//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class BOOKGRAMEntities : DbContext
{
    public BOOKGRAMEntities()
        : base("name=BOOKGRAMEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Comment> Comment { get; set; }
    public virtual DbSet<Friend> Friend { get; set; }
    public virtual DbSet<MessageList> MessageList { get; set; }
    public virtual DbSet<Person> Person { get; set; }
    public virtual DbSet<Post> Post { get; set; }
    public virtual DbSet<PostType> PostType { get; set; }
}
